spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccdb?serverTimezone=GMT%2B8&useSSL=true
    username: root
    password: xyq123456


# 配置规则
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml



server:
  port: 8888