spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared/dev


eureka:
  client:
    serviceUrl: # eureka-server的路径
      defaultZone: http://localhost:9001/eureka/