server:
  port: 9000
spring:
  application:
    name: config-server
  profiles:
    active: "dev"
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xieyuquanxx/SpringCloudConfigRepo.git/
