server:
  port: 9099


service-url:
  ie-service: http://localhost:9006
  ic-service: http://localhost:9007
  noexit-service: http://localhost:9008
  cate-service: http://localhost:9009
  daily-service: http://localhost:9010
  assess-service: http://localhost:9011
  business-service: http://localhost:9012
  termination-service: http://localhost:9013
  uncorrected-service: http://localhost:9014
  oss-service: http://localhost:9098


eureka:
  client:
    serviceUrl: # eureka-server的路径
      defaultZone: http://localhost:9001/eureka/

spring:
  cloud:
    config: # config-server的地址
      uri: http://localhost:9000
      failFast: true
    gateway:
      routes:
        - id: ie_service
          uri: ${service-url.ie-service}/ie/**
          predicates:
            - Path=/ie/**
        - id: ic_service
          uri: ${service-url.ic-service}/ic/**
          predicates:
            - Path=/ic/**
        - id: noexit_service
          uri: ${service-url.noexit-service}/noexit/**
          predicates:
            - Path=/noexit/**
        - id: cate_service
          uri: ${service-url.cate-service}/cate/**
          predicates:
            - Path=/cate/**
        - id: daily_service
          uri: ${service-url.daily-service}/daily/**
          predicates:
            - Path=/daily/**
        - id: assess_service
          uri: ${service-url.assess-service}/assess/**
          predicates:
            - Path=/assess/**
        - id: business_service
          uri: ${service-url.business-service}/business/**
          predicates:
            - Path=/business/**
        - id: termination_service
          uri: ${service-url.termination-service}/termination/**
          predicates:
            - Path=/termination/**
        - id: uncorrected_service
          uri: ${service-url.uncorrected-service}/uncorrected/**
          predicates:
            - Path=/uncorrected/**
        - id: oss_service
          uri: ${service-url.oss-service}/oss/**
          predicates:
            - Path=/oss/**