version: '3'
services:
  # 注册中心
  eureka-server:
    # 指定服务使用的镜像
    image: ccorr/eurekaserver-0.0.1:latest
    build:
      context: ./dockerfile
      dockerfile: eurekaserver-0.0.1_dockerfile
    # 指定容器名称
    container_name: eureka-server
    networks:
      - my_net
    # 指定服务运行的端口
    ports:
      - 9001:9001
  # 配置中心
  config-server:
    # 指定服务使用的镜像
    image: ccorr/configserver-0.0.1:latest
    build:
      context: ./dockerfile
      dockerfile: configserver-0.0.1_dockerfile
    # 指定容器名称
    container_name: config-server
    networks:
      - my_net
    # 指定服务运行的端口
    ports:
      - 9000:9000
  gateway:
   # 指定服务使用的镜像
    image: ccorr/gateway-0.0.1:latest
    build:
      context: ./dockerfile
      dockerfile: gateway-0.0.1_dockerfile
    # 指定容器名称
    container_name: gateway
    restart: always
    networks:
      - my_net
    # 指定服务运行的端口
    ports:
      - 9099:9099

networks:
  my_net:
    #external: true # 来自外部